#! /bin/bash

# JsonCPP need some lib before we can compile it
# apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build


OPENLIB_LIB_ZIP="libuv-1.33.1.zip"
OPENLIB_LIB_DIR="libuv-1.33.1"
OPENLIB_LIB_NAME="libuv"

echo "-----------------------------"
echo "Build "$OPENLIB_LIB_NAME" ..."


if [ -d $OPENLIB_DEST_DIR$OPENLIB_LIB_DIR  ];then
  echo $OPENLIB_LIB_NAME" Already exist"
  exit
fi



cd $OPENLIB_DEST_DIR
unzip -q $OPENLIB_SRC_DIR/$OPENLIB_LIB_ZIP
ln -s $OPENLIB_LIB_DIR $OPENLIB_LIB_NAME

mkdir -p $OPENLIB_LIB_DIR/build/release
cd $OPENLIB_LIB_DIR/build/release
cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..
make

cp libuv_a.a ../../
